# Generated by Django 4.2.7 on 2023-12-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp_secret_key',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
