# Generated by Django 4.2.7 on 2023-12-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp_expired',
            field=models.BooleanField(default=False),
        ),
    ]
