from django.urls import path
from . import views
urlpatterns = [
    path('',views.adminlogin,name='adminlogin'),
    path('adminhome/', views.adminhome, name='adminhome'),
    path('charts/', views.charts, name='charts'),
    path('order_chart/', views.order_chart, name='order_chart'),
    path('get_monthly_chart_data/',views.get_monthly_chart_data,name="get_monthly_chart_data"),
    path('get_yearly_chart_data/',views.get_yearly_chart_data,name="get_yearly_chart_data"),
    path('adminlogout',views.adminlogout,name="adminlogout"),
    path('user_management/', views.user_management_view, name='user_management_view'),
    path('edit_user/<int:user_id>/', views.edit_user_view, name='edit_user'),
    path('category_list/', views.category_list, name='category_list'),
    path('category_add/', views.add_category, name='add_category'),
     path('edit-category/<int:category_id>/', views.edit_category, name='edit_category'),
    path('delete-category/<int:category_id>/', views.delete_category, name='delete_category'),
    path('category/toggle_listing/<int:category_id>/', views.toggle_category_listing, name='toggle_category_listing'),
    path('product/toggle_listing/<int:category_id>/', views.toggle_product_listing, name='toggle_product_listing'),
    path('product_list/', views.product_list, name='product_list'),
    path('add_product/', views.add_product, name='add_product'),
    path('edit_product/<int:product_id>/', views.edit_product, name='edit_product'),
    path('add_variant/<int:product_id>/', views.add_variant, name='add_variant'),
    path('delete_product/<int:product_id>/',views.delete_product,name="delete_product"),
    path('admin_orders/', views.admin_orders, name='admin_orders'),
    path('update_order_status/<int:orderid>', views.update_order_status, name='update_order_status'),
    path('add_new_coupon/',views.add_new_coupon,name="add_new_coupon"),
    path('coupon_list/',views.coupon_list,name="coupon_list"),
    path('generate_coupon_code/',views.generate_coupon_code,name="generate_coupon_code"),
    path('add_new_coupon/',views.add_new_coupon,name="add_new_coupon"),
    path('order_view/<str:oid>/',views.admin_order_detail, name="order_view"),
    path('productoffer/',views.productoffer,name="productoffer"),
    path('categoryoffer/',views.categoryoffer,name="categoryoffer"),
    path('add_offer/',views.addoffer,name="add_offer"),
    path('add_category_offer/',views.add_category_offer,name="add_category_offer" ),
    path('adminhome/', views.adminhome, name='adminhome'),

] 