# Generated by Django 4.2.7 on 2024-01-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_productoffer_categoryoffer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryoffer',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='categoryoffer',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='productoffer',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='productoffer',
            name='start_date',
        ),
        migrations.AddField(
            model_name='variant',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
