# Generated by Django 4.2.7 on 2023-12-28 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_remove_productimages_variant_productimages_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='size',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
