# Generated by Django 4.2.7 on 2024-01-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_remove_categoryoffer_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='categoryoffer',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
