# Generated by Django 4.2.7 on 2024-01-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_variant_discount_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='stock_added',
            field=models.IntegerField(default=0),
        ),
    ]
