# Generated by Django 4.2.7 on 2023-12-28 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_color_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='product',
        ),
    ]
