# Generated by Django 4.2.7 on 2023-12-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0005_remove_color_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
    ]
