# Generated by Django 4.2.7 on 2024-01-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_order_coupon_code_order_coupon_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycoupons',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mycoupons',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
