# Generated by Django 4.2.7 on 2024-01-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_mycoupons_is_disabled_alter_mycoupons_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Returned', 'Returned'), ('Paid', 'Paid')], max_length=100),
        ),
    ]
