# Generated by Django 4.2.7 on 2023-12-29 17:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0006_variant_is_listed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cart',
            new_name='cartitems',
        ),
    ]
