# Generated by Django 4.2.7 on 2024-01-03 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_order_address_order_order_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
