# Generated by Django 4.2.7 on 2024-01-07 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_rename_appliedcoupon_userappliedcoupon_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCoupons',
            new_name='MyCoupons',
        ),
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
    ]
